#!/bin/bash

OPTIND=1
FORMAT="csv"
HEADER='HEADER'

show_help() {
    echo "$1 [-f FORMAT] [-H]"
    echo ""
    echo "-f = The format to output (csv, tsv or ndjson)"
    echo "-H = Skip adding the header (for csv or tsv)"
    echo ""
    exit 0
}

while getopts "hHf:" opt; do
    case "$opt" in
        H)
            HEADER=''
            ;;
        h)
            show_help
            exit 0
            ;;
        f)  FORMAT="$OPTARG"
            ;;
    esac
done
shift $(( OPTIND - 1 ))


if [ -z "$FORMAT" ]; then
    show_help
    exit 1
fi

if [ "ndjson" != "$FORMAT" ] && [ "csv" != "$FORMAT" ] && [ "tsv" != "$FORMAT" ]; then
    show_help
    exit 1
fi

IN_SQL=""
while read line
do
    IN_SQL="${IN_SQL} $line"
done < "/dev/stdin"


if [ -z "$IN_SQL" ]; then
    IN_SQL=$2
fi

set -euo pipefail
IFS=$'\n\t'

UUID=$(uuidgen | sed 's/\-//g')

OUT_TSV="COPY (${IN_SQL}) TO STDOUT WITH CSV ${HEADER} NULL AS '' DELIMITER AS E'\t'"
OUT_CSV="COPY (${IN_SQL}) TO STDOUT WITH CSV ${HEADER} NULL AS ''"
OUT_NDJSON="select row_to_json(x$UUID) from ( $IN_SQL ) x$UUID"

OUT="$OUT_TSV"
if [ "csv" == "$FORMAT" ]; then
    OUT="$OUT_CSV"
fi
if [ "ndjson" == "$FORMAT" ]; then
    OUT="$OUT_NDJSON"
fi

echo "$OUT" | psql -t | grep -v '^$'  | sed 's/^\s\+//'

exit $?
